# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b33b3cc26a0d7326805a5fbb070cd5f0ca46acb642395f5bc48dea6a6606f74e135043e5f2c07660a6dae673008e6792037f82af4018aee6748ac06707f5be1

test:
  secret_key_base: fe96dbbb74da3689d917763e57bb5359f594db49787ad01ba43978bf2ff8f8b14a9ad5c94aefcdfcfac72e3a4c6d781e27ded630bb568d410a4b58ba14dcd999

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
